{"name": "Проверка ошибки при авторизации курьера с несуществующими данными", "status": "passed", "description": "Отправляем запрос на авторизацию в сервисе с несуществующими данными и проверяем ответ", "start": 1719311646684, "stop": 1719311646929, "uuid": "3ecd66c1-fb0d-4a41-9321-ba23c4002643", "historyId": "7d6c240669be102bb96f7f568dd3ce34", "testCaseId": "7d6c240669be102bb96f7f568dd3ce34", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_without_null_login_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WIN-DIQJIRLC2O2"}, {"name": "thread", "value": "23404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}